apiVersion: v1
kind: Pod
metadata:
  name: mrx-preprod
  labels:
    app: mrx-preprod
spec:
  hostname: mrx-preprod
  containers:
  - name: clean
    image: ghrc.io/functionally/marlowe-clean:latest
    env:      
    - name: PGHOST       
      value: host.containers.internal
    - name: PGPORT     
      value: 5432
    - name: PGUSER           
      value: cardano
    - name: PGPASSWORD         
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: NETWORK
      value: preprod  
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    - name: CARDANO_TESTNET_MAGIC
      value: 1
    - name: MARLOWE_RT_HOST
      value: mrt-preprod
    - name: MARLOWE_RT_PORT
      value: 3780
    - name: PAYMENT_ADDR
      value: addr_test1qquu8u4aqtx8nrlazflvztkcuh5ed9xs389t6q27vqzjysynjlzdfawd9kvva673fht7737e3r5j322v7090uqhpn0wqm0wc0h
    - name: PAYMENT_SKEY
      value: /keys/payment.skey
    volumeMounts:    
    - mountPath: /ipc
      name: shared      
    - mountPath: /keys
      name: keys      
  volumes:
  - name: shared
    hostPath:
      type: Directory
      path: ./.
  - name: keys
    hostPath:
      type: Directory
      path: ./keys
  restartPolicy: Never
